### ISSUE TITLE
README on Node-Red isn't updated

### ISSUE THREAD

**Issue by moritonal** [bartbutenaers/node-red-contrib-alexa-notifyme#6]
Hihi

I see you've fixed the README so it doesn't show a 404, but it doesn't seem to have propagated to Node-Red's page so it looks like it's broken.

https://flows.nodered.org/node/node-red-contrib-alexa-notifyme

Tom

**Comment by bartbutenaers** [comment]
Hi Tom,

thanks for reporting the desync between Github and NPM.
I have published it on NPM as version **1.0.2**, and the link seems now the same to me:

![image](https://user-images.githubusercontent.com/14224149/70750173-297d4c80-1d2e-11ea-9743-bf09474058e8.png)

Please close this issue if your problem is solved!
Bart

**Comment by moritonal** [comment]
Amazing turn-around time. Using this now and it's working great!
